### ISSUE TITLE
Original label is removed upon saving a previously pulled story

### ISSUE THREAD

**Issue by whysthatso** [dashofcode/tracker_api#104]
Hey,
not sure if i'm using the gem in the right way.

these are they steps:

```
client = TrackerApi::Client.new token: token
project = client.project project_id
story = project.story story_id

story.create_comment text: comment_text
story.estimate = estimation
story.current_state = new_state
story.save
```

- comment is created
- new state is set
- estimate is changed

but also the original label is gone. btw, the label also represents an epic.

i'm following a quite procedural approach here, so maybe there's the problem?

**Comment by forest** [comment]
@whysthatso I created a test for this and don't see the behavior you are reporting. Can you create a test that reproduces the issue?

**Comment by whysthatso** [comment]
thanks a bunch for your efforts. I can see that your test reproduces my functionality.

however, i cannot really follow your question if reproducing that issue in a test.

I'm just running this in 'irb' against a pt board.

Also, i reduced the script to literally just getting this story object, and without changes saving it again, which also results in both labels (one simple, one associated with an epic) to be removed from the story.

if you can give me a hint how to create the test then i can certainly try.

**Comment by whysthatso** [comment]
addendum
as far as i understand you are merely mocking the pt api in your tests, right?
how could i verify that your test mock, and the actual pt api return the same results?

**Comment by cog-kaurikk** [comment]
Having the same issue (have not noticed it before, but seems i have removed all the labels from lots of my storys).

**Comment by forest** [comment]
The VCR mock is created by doing a real run of the test against the live PT. The response from PT is recorded and saved to speed up future tests. If you delete the VCR files for the test PT will be hit live and the file recreated.

I will try to reproduce in irb.

**Comment by forest** [comment]
I was able to reproduce the bug in irb. Not sure why they test didn't reproduce it.

**Comment by forest** [comment]
@whysthatso @cog-kaurikk can you pull the #106 branch and see if this fixes your issue?

I reran all the tests clean against the live PT.

**Comment by whysthatso** [comment]
yup, that did it.

do i understand your fix right that you replaced an empty array with nil to make it work? just curious.

**Comment by forest** [comment]
@whysthatso thanks for confirming. Yes, that was the fix. I'll update the pull request with details of why.
