### ISSUE TITLE
Upload attachments

### ISSUE THREAD

**Issue by kirykr** [dashofcode/tracker_api#105]

**Comment by forest** [comment]
This is not supported yet. Pull requests welcome.

**Comment by moonshineJMU** [comment]
Any idea when this would be added?

**Comment by forest** [comment]
I don't have a use case for this so it is low on my list. Pull requests are
always welcome.

**Comment by s-ashwinkumar** [comment]
Some basic use cases I could see (maybe in decreasing order of priority as I see.) : 
- As a user, I would like to be able to add an attachment to the comment I am adding.
- As a user, I would like to be able to remove an attachment from an existing comment.
- As a user, I would like to be able to add an attachment to an existing comment.
- As a user, I would like to replace an attachment on a comment with another one.

I was developing a chatbot and stumbled upon this repository. Would be more than happy to add these functionalities. Please let me know.

**Comment by forest** [comment]
Contributions are welcome. I'm happy to help review and provide any guidance you need. Thanks.

**Comment by s-ashwinkumar** [comment]
PR : https://github.com/dashofcode/tracker_api/pull/108
