### ISSUE TITLE
project.search method does not work

### ISSUE THREAD

**Issue by tverbrugge-athn** [dashofcode/tracker_api#121]
I tried using this wrapper's search method with no luck. I tried 

```project.search('Destroy death star')``` 

after setting up the client and the project variables correctly.

**Comment by jakemmarsh** [comment]
@tverbrugge-athn what error were you seeing? I'm currently getting a 400, `Your client has issued a malformed or illegal request.  That's all we know.`

**Comment by mattyohe** [comment]
The issue appears to be here:
https://github.com/dashofcode/tracker_api/blob/master/lib/tracker_api/endpoints/search.rb#L13

Unsure what the intent of the `options[:body][:query]` hash is, instead fixing it this way:
`options[:params] = { query: query }`

**Comment by forest** [comment]
@mattyohe I think the intent was not to overwrite an existing `body`. Also, need to make sure not to overwrite existing `options[:params]`.

Want to send a pull request?
