### ISSUE TITLE
Issue w/ JRuby cipher set

### ISSUE THREAD

**Issue by bmulvihill** [dashofcode/tracker_api#123]
I was attempting to get this gem working with a project and ran into an issue (currently using Jruby 9.1.17.0) related to the http adapter.  By default the gem will select `excon` adapter which throws the following error for Jruby related to ciphers.

`<Faraday::ConnectionFailed wrapped=#<Excon::Error::Socket: no cipher match (OpenSSL::SSL::SSLError)>`

I found this issue https://github.com/excon/excon/issues/528

It seems the Excon default Cipher set is too restrictive for JRuby.  We can circumvent this by specifying another adapter, but maybe if a user is on Jruby this should be by default?

**Comment by forest** [comment]
@bmulvihill Thanks for the analysis. I'm open to another default adapter for JRuby or changing the cipher for JRuby per the linked issue.

Interested in submitting a pull request for this?

**Comment by bmulvihill** [comment]
@forest I am unfamiliar w/ Excon and the benefits it provides vs. other http clients, would there be any detriment to using `net_http` for Jruby?
