### ISSUE TITLE
Add ability to add project memberships

### ISSUE THREAD

**Issue by bboe** [dashofcode/tracker_api#34]
https://www.pivotaltracker.com/help/api/rest/v5#projects_project_id_memberships_post

The work-a-round I added in my code
https://github.com/bboe/pttool/blob/master/lib/pttool/helper.rb#L13

**Comment by newOnahtaN** [comment]
This should be resolved now: https://github.com/dashofcode/tracker_api/pull/40

**Comment by forest** [comment]
I'll try to get a new version released this week.
