### ISSUE TITLE
Project labels broken

### ISSUE THREAD

**Issue by wdhays2** [dashofcode/tracker_api#45]
Labels on the project only returns an empty array. The reason is the API no longer has labels directly on the project response. A separate call to projects/{project_id}/labels needs to happen. 
I have submitted a pull request for the fix.

**Comment by forest** [comment]
The API didn't change. Just need to use the fields param to get label in one request.

Your pull is a nice addition that allow for getting the labels with an extra request if you didn't plan on needing them from the beginning.
