### ISSUE TITLE
Can't  move story between projects

### ISSUE THREAD

**Issue by fuadsaud** [dashofcode/tracker_api#68]
Seems like if I set the `project_id` for some story it fails to update the resource: it tries to `PUT` the story on a nested route under the new `project_id`, which will fail with a 404 since that story doesn't belong to that project.

Is there any know workaround for this or it'll require some tweaking on the `Story` object?

**Comment by forest** [comment]
Moving a story between projects is not supported. Pull requests welcome.

**Comment by fuadsaud** [comment]
@forest cool! shouldn't be difficult to implement. I'll see if I can come up with something tonight.

**Comment by TimKJones** [comment]
Just put up a pull request for this issue: https://github.com/dashofcode/tracker_api/pull/128
