### ISSUE TITLE
Adding comments to a story

### ISSUE THREAD

**Issue by samsonasu** [dashofcode/tracker_api#83]
First off thanks for all the work -- we recently updated to the v5 api and this gem has been super helpful. 

It looks to me like there's no way currently in this gem to add comments to a story.  I'm happy to help implement that feature but I wanted to first check that I wasn't missing something obvious or looking in the wrong place.

I think the closest pattern to copy here is how story tasks work, so just implement save/update on `Comment`.  Does that sound right? 

Thanks again ❤️

**Comment by forest** [comment]
Yep. You can get comments now, but not create or update them. Copy the pattern for `Task`. Should be pretty straight forward. 

Don't forget the tests.  :)
