### ISSUE TITLE
Error when trying to retrieve a story

### ISSUE THREAD

**Issue by nrodriguez** [dashofcode/tracker_api#96]
When trying to access an individual story, I get:

```ruby
>>> @pivotal.project.story(123)
NameError: uninitialized constant TrackerApi::Endpoints::Story
Did you mean?  TrackerApi::Endpoints::Stories
from /GEM_PATH_HERE/tracker_api-0.1.0/lib/tracker_api/resources/project.rb:82
```

Doing a manual ```require 'tracker_api/endpoints/story'``` fixes the issue though. It seems to be related to the autoloading, I believe?

**Comment by drselump14** [comment]
the latest gem version is 1.6.0 and you're using 0.1.0 version... probably that's the issue

**Comment by forest** [comment]
Thanks @drselump14. Please reopen if the latest version has issues.
